### ISSUE TITLE
Bug: Obsolete function contexts

### ISSUE THREAD

**Issue by haensl** [chrisdothtml/pfs#1]
Most, if not all, the functions implemented have no need for a context => Replace with arrow functions.

**Comment by haensl** [comment]
PR open https://github.com/chrisdothtml/pfs/pull/2

**Comment by chrisdothtml** [comment]
If it's not causing an implementation to break, I'd hesitate to call it a bug. Function contexts are **not** obsolete, and there's [no performance gain to be had](https://stackoverflow.com/a/44031830/2880820) from switching to arrow functions.

This package was written with support of almost all node versions in mind, which is why some newer ES features were left out. Some of those features could be included, but instead of investigating node support for every feature, I decided to stick to the basics.

Switching from `var` to `const` is the only thing I'd really understand griping over, but even then, this package is so small, it's very unlikely that any syntactical change could significantly impact performance

**Comment by haensl** [comment]
OK, fine with me. Then I'll do what I was asked to do in the first place and publish something similar if you don't mind.
The main reason why I made this pull request is that I know quite a few people (including myself) who would like to use your module, but do not since it is not written in a _tight_ way. Sometimes people avoid small packages that are already "sloppy" (no offense intended), since these things kind of add up.
